### ISSUE TITLE
"Unable to find a passphrase" error output as a password

### ISSUE THREAD

**Issue by AeroNib** [ligos/readablepassphrasegenerator#11]
When the plugin cycles through passwords and checks them against min and max length rules, it discards passwords that do not meet the rules, but it also then outputs an error message in place of the password. This means that sometimes the generated password in KeePass2 is the error message itself.

![Error in Password Field](https://user-images.githubusercontent.com/48144540/117013464-e70b3580-acbd-11eb-9d40-4313ae6b32ee.png)

![Errors in Preview](https://user-images.githubusercontent.com/48144540/117013495-eecada00-acbd-11eb-9ba2-12acd5263599.png)

### System Info

Plugin version v1.2.1
KeePass version 2.44
Running on Windows 10 v 2004 build 19041.928

**Comment by ligos** [comment]
Thanks for the report.

The plugin does not get any indication it's creating a password on the Preview tab vs the real Password field. So my options are:

* Return an empty password when I can't find one - not a big fan because it's not clear what went wrong.
* Increase the number of times the generator tries for a password before giving up - it's currently 1000. Changing to 10,000 would make your case happen 1/10 as often. Which is better, but not a real fix.
* Ask you to increase your length criteria - 24 characters should work much better! The longer the better.

Murray
