### ISSUE TITLE
Depend on mono-runtime instead of mono-complete

### ISSUE THREAD

**Issue by theHilikus** [ligos/readablepassphrasegenerator#16]
For linux users, pulling all of `mono-complete` just to run a single keepass plugin seems excessive. Would it be very hard to use only what's available in mono-runtime? What parts exactly need mono development tools?

**Comment by ligos** [comment]
My recommendation for `mono-complete` is based on experience from ~10 years ago. And a lot has changed since then. I'm unsure exactly what parts of plugin / KeePass need development tools - however I do know KeePass compiles plugins on each new version (of KeePass), which may be part of the reason.

I agree it is excessive, but was aiming for "make it work" rather than "make it perfect". If you have some time to dissect `mono-complete` and experiment with which individual packages are required, I'm happy to update the wiki with a specific list.

**Comment by theHilikus** [comment]
ok, i see. it makes perfect sense

I don't really know much about mono, sorry. i was just inquiring if you knew how much effort it would be in case it could be a quick win for me to try.

thank you
