### ISSUE TITLE
Why not adding also Diceware?

### ISSUE THREAD

**Issue by marcoXbresciani** [ligos/readablepassphrasegenerator#5]
It could be nice to also introduce the Diceware algorithm to generate the phrase: https://theworld.com/~reinhold/diceware.html

Also this: https://www.eff.org/it/dice

**Comment by ligos** [comment]
Sorry, no.

There are already other [Passphrase Generator Plugins for KeePass](https://keepass.info/plugins.html#ppgen) that pick words at random from a list. The [Console App](https://github.com/ligos/readablepassphrasegenerator/wiki/How-to-Use-the-Console-App) can generate non-grammatical phrases with the `-n` option.

And one of Diceware's important points is the random number generator is totally transparent. If you really want to use Diceware, go roll some dice rather than trust the crazy complex math required to make a deterministic computer generate random numbers!

> **I have an electronic dice throw generator. Should I use it?**
> No! Unless you know how the electronics generate the randomness and can evaluate its strength, stick to old-fashioned real dice.

> **Can I use a computer to generate Diceware passphrases?**
> Generating truly random numbers using a computer is very tricky. The so-called random number generators that come with most programming libraries are nowhere near good enough. For most users dice is by far a better way to select passphrase words.
